# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.4.5
maven_group = multiteam
archives_name = garden-arsenal
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.6
fabric_loader_version = 0.16.3
fabric_api_version = 0.103.0+1.21.1
forge_version = 1.21.1-52.0.9
neoforge_version = 21.1.31
rei_version = 16.0.754
modmenu_version = 11.0.2
jei_version = 19.11.0.130
