# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.4.6
maven_group = multiteam
archives_name = garden-arsenal
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4

# Dependencies
architectury_api_version = 15.0.3
fabric_loader_version = 0.16.8
fabric_api_version = 0.119.4+1.21.4
forge_version = 1.21.4-54.1.6
neoforge_version = 21.4.154
rei_version = 18.0.808
modmenu_version = 13.0.3
jei_version = 20.0.0.4
