# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.4.6
maven_group = multiteam
archives_name = garden-arsenal
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.20.5

# Dependencies
architectury_api_version = 12.0.29
fabric_loader_version = 0.15.11
fabric_api_version = 0.97.8+1.20.5
forge_version = 1.20.4-49.1.4
neoforge_version = 20.5.21-beta
rei_version = 15.0.743
modmenu_version = 10.0.0
jei_version = 17.3.1.3
